on:
  push:
    branches:
    - developer

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
    uses: diillson/auto-pull-request@latest
      with:
        destination_branch: "main"